---
- name: Build and redeploy Docker container
  hosts: localhost
  tasks:

    - name: Stop current running container (ignore errors if not exists)
      command: docker stop web-container
      ignore_errors: yes

    - name: Remove stopped container (ignore errors if not exists)
      command: docker rm web-container
      ignore_errors: yes

    - name: Remove old Docker image (ignore errors if not exists)
      command: docker rmi simple-project-img
      ignore_errors: yes

    - name: Build new Docker image
      command: docker build -t simple-project-img .

    - name: Run container
      command: docker run -d --name web-container -p 8080:8080 simple-project-img

